# 파일 규격 버전
version: '3'
# 이 항목 밑에 실행하려는 컨테이너 들을 정의
services:
  nginx:
    container_name: echo-nginx
    image: mynginx:0.0.1
    links:
      - app-1:app-1
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app-1
    volumes:
      - /etc/ssl:/etc/nginx/certs
    networks:
      - echo_net

  app-1:
    container_name: echo-1
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - echo_net
  app-2:
    container_name: echo-2
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - echo_net
  app-3:
    container_name: echo-3
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - echo_net
  app-4:
    container_name: echo-4
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - echo_net

networks:
  echo_net:
    driver: bridge