# 파일 규격 버전
version: '3'
# 이 항목 밑에 실행하려는 컨테이너 들을 정의
services:
  nginx:
    container_name: echo-nginx
    image: mynginx:${nginx}
    links:
      - app-1:app-1
      - app-2:app-2
      - app-3:app-3
      - app-4:app-4
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/ssl/echo:/etc/nginx/certs
    networks:
      - echo_net

  app-1:
    container_name: echo-1
    image: echo-server:${server}
    networks:
      - echo_net
  app-2:
    container_name: echo-2
    image: echo-server:${server}
    networks:
      - echo_net
  app-3:
    container_name: echo-3
    image: echo-server:${server}
    networks:
      - echo_net
  app-4:
    container_name: echo-4
    image: echo-server:${server}
    networks:
      - echo_net

networks:
  echo_net:
    driver: bridge